spring:
  datasource:
    url: jdbc:mysql:///mybatis_plus
    username: root
    password: zjf200014
    # type：数据库类型
    driver-class-name: com.mysql.cj.jdbc.Driver

#    druid:
#      filters: stat,wall,slf4j
#
#      stat-view-servlet:
#        enabled: true
#        login-username: admin
#        login-password: 123
#        reset-enable: false

#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

#      aop-patterns: com.zjf.admin.*
#
#      filter:
#        stat:
#          slow-sql-millis: 1000
#          log-slow-sql: true
#          enabled: true
#        wall:
#          enabled: true
#          config:
#            drop-table-allow: false

  #   type: com.zaxxer.hikari.HikariDataSource 默认就是整个

#  jdbc:
#    template:
#      query-timeout: 3

#redis://user:password@example.com:6379
#  redis:
#    host: r-bp1kf1g0n5t4ip1y01pd.redis.rds.aliyuncs.com
#    port: 6379
#    password: zjf:Zjf200014
    # url: redis://Zjf200014@r-bp1kf1g0n5t4ip1y01pd.redis.rds.aliyuncs.com:6379
  boot:
    admin:
      client:
        url: http://localhost:9999

#management 是所有acturator的配置
# management.endpoint.端点名.xxx 对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点

  endpoint:
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

info:
  appName: boot-admin
  addVersion: 1.0.0
  mavenProjectName: @project.artifactId@
